name: Nginx-1.22.1
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@v3

      - name: install dependent
        run: |
          yum install -y rpm-build pcre2-devel gcc gcc-c++ make cmake automake autoconf gd file bison patch mlocate flex diffutils zlib zlib-devel pcre pcre-devel libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel libxml2 libxml2-devel glibc glibc-devel glib2 glib2-devel bzip2 bzip2-devel ncurses ncurses-devel curl curl-devel libcurl libcurl-devel e2fsprogs e2fsprogs-devel krb5 krb5-devel openssl openssl-devel  kernel-devel libtool-libs readline-devel gettext-devel libcap-devel php-mcrypt libmcrypt libmcrypt-devel recode-devel

          
      - name: create user and switch
        run: |
          useradd -m -p test_pass macros
          echo "%_topdir /home/macros/rpmbuid" >/home/macros/.rpmmacros
          su macros

      - name: create rpmbuid
        run: |
          mkdir -p /github/home/rpmbuild

      - name: prep sources
        run: |
          mv /__w/Nginx-1.22.1/Nginx-1.22.1/SPECS /github/home/rpmbuild/
          mv /__w/Nginx-1.22.1/Nginx-1.22.1/SOURCES /github/home/rpmbuild/


      - name: make
        run: |
          cd /github/home/rpmbuild/SPECS
          su macros
          rpmbuild -bb nginx.spec
