name: Nginx-1.22.1
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@v3

      - name: install dependent
        run: |
          yum install -y rpm-build wget tar gcc automake autoconf libtool make vim net-tools
          
      - name: create user and switch
        run: |
          useradd -m -p test_pass macros
          echo "%_topdir /home/macros/rpmbuid" >/home/macros/.rpmmacros
          su macros

      - name: create rpmbuid
        run: |
          mkdir -p /home/macros/rpmbuid
          

      - name: prep sources
        run: |
          mv /__w/Nginx-1.22.1/Nginx-1.22.1/SPECS /home/macros/rpmbuid
          ls /home/macros/rpmbuid/*
          mv /__w/Nginx-1.22.1/Nginx-1.22.1/SOURCES /home/macros/rpmbuid
          ls /home/macros/rpmbuid/*
          pwd
          ls -a /home/macros

      - name: make
        run: |
          cd /home/macros/rpmbuid/SPECS
          su macros
          pwd
          rpmbuild -bb nginx.spec
