name: GitHub Actions Demo
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@v2

      - name: install dependent
        run: |
          yum install -y rpm-build wget tar gcc automake autoconf libtool make vim net-tools
          

