name: Nginx-1.22.1
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@v3

      - name: install dependent
        run: |
          yum install -y rpm-build wget tar gcc automake autoconf libtool make vim net-tools
          
      - name: create user and switch
        run: |
          useradd -m -p test_pass macros
          su macros
          find /* -name SPECS
          cat /etc/redhat-release
          
